# Generated by Django 6.0.8 on 2026-08-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('age', models.IntegerField(verbose_name='Âge')),
                ('gender', models.CharField(max_length=10, verbose_name='Sexe')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('medical_notes', models.TextField(blank=True, verbose_name='Notes médicales')),
                ('admission_date', models.DateField(auto_now_add=True, verbose_name="Date d'admission")),
            ],
        ),
    ]
