# Generated by Django 6.0.8 on 2026-08-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'verbose_name': 'Résident', 'verbose_name_plural': 'Résidents'},
        ),
        migrations.RemoveField(
            model_name='resident',
            name='age',
        ),
        migrations.AddField(
            model_name='resident',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Allergies'),
        ),
        migrations.AddField(
            model_name='resident',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='resident',
            name='diseases',
            field=models.TextField(blank=True, verbose_name='Maladies'),
        ),
        migrations.AddField(
            model_name='resident',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=150, verbose_name='Personne à contacter'),
        ),
        migrations.AddField(
            model_name='resident',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name="Téléphone d'urgence"),
        ),
        migrations.AddField(
            model_name='resident',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='resident',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observations'),
        ),
        migrations.AddField(
            model_name='resident',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='residents/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='resident',
            name='status',
            field=models.CharField(choices=[('active', 'Présent'), ('left', 'Parti'), ('hospital', 'Hospitalisé')], default='active', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='resident',
            name='treatments',
            field=models.TextField(blank=True, verbose_name='Traitements'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='admission_date',
            field=models.DateField(verbose_name="Date d'admission"),
        ),
        migrations.AlterField(
            model_name='resident',
            name='gender',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1, verbose_name='Sexe'),
        ),
    ]
