# Generated by Django 6.0.8 on 2026-08-13 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='residents.room', verbose_name='Chambre'),
        ),
    ]
